lrn_magazine:
    resource: "@LrnMagazineBundle/Controller/"
    type:     annotation
    prefix:   /

_user_bundle:
    resource: "@LrnUserBundle/Resources/config/routing.yml"

app:
    resource: @AppBundle/Controller/
    type:     annotation
